include: package:flutter_lints/flutter.yaml

linter:
  rules:

# freezed issue
# https://github.com/rrousselGit/freezed/issues/488
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore
